package com.seankrail.coursegrabber.java;

public enum BuildingEnum {
	AED ("Amy du Pont Music Building"),
	AFR ("ROTC, 314 Wyoming Road"),
	ALS ("Alison Hall"),
	ALW ("Alison Hall West"),
	ART ("Art Studio Building"),
	BCC ("Bob Carpenter Center"),
	BRL ("Brown Laboratory"),
	BSH ("Bayard Sharp Hall"),
	CFA ("Center for the Arts"),
	CLB ("Colburn Lab"),
	CMU ("Courtyard by Marriot at UD"),
	CSB ("Carpenter Sports Building"),
	DFH ("Delaware Field House"),
	DUP ("Du Pont Hall"),
	ELT ("Elliott Hall"),
	EST ("East Hall"),
	EVN ("Evans Hall"),
	EWG ("Ewing Hall"),
	FGL ("Fischer Greenhouse Laboratory"),
	GOR ("Gore Hall"),
	GRH ("Greenhouse"),
	GRM ("Graham Hall"),
	HGY ("Hartshorn Hall"),
	HUL ("Hullihen Hall"),
	ICE ("Ice Arena (Gold)"),
	ISE ("Interdisciplinary Science and Engineering Laboratory"),
	JMC ("Clayton Hall"),
	JMH ("Munroe Hall"),
	KRB ("Kirkbride Lecture Hall"),
	LDL ("Lammot du Pont Laboratory"),
	LEH ("Alfred Lerner Hall"),
	LIN ("Linguistics, 46 East Delaware Avenue"),
	MDH ("McDowell Hall"),
	MEH ("Mechanical Hall"),
	MEM ("Memorial Hall"),
	MIL ("Taylor Hall Annex"),
	MKL ("McKinly Laboratory"),
	MLB ("Morris Library"),
	MTH ("Mitchell Hall"),
	OCL ("Old College"),
	OEL ("Ocean Engineering Laboratory"),
	PBG ("Newton Poultry Building"),
	PNY ("Penny Hall"),
	PRN ("Purnell Hall"),
	PRS ("Pearson Hall"),
	QDH ("Quaesita Drake Hall"),
	RBH ("Raub Hall"),
	REC ("Recitation Hall"),
	ROB ("Robinson Hall"),
	SCN ("Theatre Scene Shop"),
	SHL ("Sharp Laboratory"),
	SMI ("Smith Hall"),
	SPL ("Spencer Laboratory"),
	SSC ("Ice Arena (Fred Rust)"),
	STC ("Perkins Student Center"),
	STS ("Student Services Building"),
	TNS ("Townsend Hall"),
	TUC ("Trabant University Center"),
	TYG ("Taylor Hall"),
	WFM ("Webb Farm"),
	WHL ("Williard Hall Education Building"),
	WLF ("Wolf Hall"),
	WOR ("Worrilow Hall");
	
	private final String title;
	
	BuildingEnum(String title) {
		this.title = title;
	}
	
	public String getTitle() {return this.title;}
}
